name: 'Upload DApp to IPFS W3Auth Gateway'
description: 'Upload your DApp to IPFS W3Auth Gateway'
author: 'Decoo Technologies'
branding:
  icon: 'upload'
  color: 'gray-dark'

inputs:
  path:
    description: 'Path to directory which should be sent to gateway'
    required: true
  seeds:
    description: 'Substrate-based chain secret seeds'
    required: true
  gateway:
    description: 'IPFS gateway which support web3 authentication'
outputs:
  hash:
    description: 'Uploaded IPFS cid(CIDv0) hash value'

runs:
  using: 'node12'
  main: 'dist/index.js'