on: 
  push:
    branches:
      - main

jobs:
  test_job:
    runs-on: ubuntu-latest
    name: Testing on Crust IPFS uploader
    steps:
      - uses: actions/checkout@v2.1.0
      - name: Crust IPFS uploader action
        id: pin
        uses: crustio/ipfs-upload-action@v2.0.0
        with:
          path: './.github/workflows/build'
          seeds: ${{ secrets.CRUST_SEEDS }}
      - name: Got it
        run: echo "Access with 'https://crustwebsites.net/ipfs/${{ steps.pin.outputs.hash }}'"
